---

name: Build
run-name: Build process for CyCAx
on: [push]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    container:
      image: gitea.tu.tsolo.net/tsolo/ubuntu:22-ci
    steps:
      - name: Checkout repository code
        uses: https://gitea.com/actions/checkout@v4
      - name: Run tests
        run: make test 
      - name: Package with Python
        run: make build
      - name: get local version
        run: echo "LOCAL_VERSION=$(hatch version)" >> $GITHUB_ENV
      - name: get packaged versions
        run: echo "PACKAGED_VERSIONS=\"$(pip index versions cycax --index-url https://gitea.tu.tsolo.net/api/packages/tsolo/pypi/simple | tr -d '\n')\"" >> $GITHUB_ENV
      - name: Publish Python package
        run: |
          hatch --verbose publish -r https://${{ vars.REGISTRYHOST }}/api/packages/tsolo/pypi -u ${{ vars.REGISTRYUSER }} -a ${{ secrets.REGISTRYPASSWORD }}
          pip index versions cycax --index-url https://gitea.tu.tsolo.net/api/packages/tsolo/pypi/simple
        if: ${{ !contains(env.PACKAGED_VERSIONS, env.LOCAL_VERSION) }}
