# SPDX-FileCopyrightText: 2026 Tsolo.io
#
# SPDX-License-Identifier: Apache-2.0

---

name: Documentation
run-name: Docs
on: [push]

jobs:
  test:
    runs-on: "ubuntu-24.04"
    container:
      image: gitea.tu.tsolo.net/tsolo/ubuntu:24-ci
    steps:
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v4
      - name: Make docs and upload
        uses: https://gitea.tu.tsolo.net/Tsolo/make-docs-upload-action@main
        with:
          s3_endpoint: http://192.168.100.41:7480
          s3_bucket: documentation
          s3_access_key: ${{ vars.S3_DOC_ACCESS }}
          s3_secret_key: ${{ secrets.S3_DOC_SECRET }}
