name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install hatch
      run: pip install hatch
    
    - name: Run linting
      run: hatch run lint:all
    
    - name: Run tests (non-slow)
      run: hatch run testing:ci
    
    # - name: Run tests with coverage
    #   if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
    #   run: hatch run testing:cov
    # 
    # - name: Upload coverage to Codecov
    #   if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
    #   uses: codecov/codecov-action@v3
    #   with:
    #     fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install hatch
      run: pip install hatch
    
    - name: Build package
      run: hatch build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
